### ISSUE TITLE
server: System monitoring

### ISSUE THREAD

**Issue by zven** [mint-o-badges/badgr-server#40]
We should set up some way of system monitoring. This could be via prometheus and grafana, but maybe also something low level, like UptimeRobot, would suffice. There are already tickets for prometheus / grafana, but since I feel a need for discussing this, I created this ticket.

**Comment by zven** [comment]
UptimeBot

**Comment by timber-they** [comment]
I've set up uptimerobot with my timber@opensenselab.org mail address. Since the free plan doesn't allow for multiple addresses to send mails too, I've set up my mail client on my phone to forward mails from alert@uptimerobot.com to other team members mail addresses. The mails get forwarded from timber@systemli.org, my personal mail, because my opensenselab mail identity doesn't quite seem to work (yet).
If you didn't receive the test mail but want to be notified, write me your mail address.

**Comment by mpfeil** [comment]
In other projects we use Uptime Kuma https://github.com/louislam/uptime-kuma it is a self-hosted monitoring system. 

I would definitely set up Grafana with Prometheus for monitoring system resources and would recommend setting up Grafana Loki for logging. 

https://grafana.com/oss/loki/
