### ISSUE TITLE
install meinBildungsraum connector

### ISSUE THREAD

**Issue by zven** [mint-o-badges/badgr-server#59]
Todos:
- [x] book and set up smallest possible hetzner server
- [x] install and configure (?) connector docker container

**Comment by zven** [comment]
see 240402_Anbindungstutorial_Mein_Bildungsraum_V5.pdf, chapter "3.2 Installation Connector & Ablage"

**Comment by timber-they** [comment]
I've set up a minimal debian server under 159.69.11.183, asked Christopher to create a subdomain for it (connector.openbadges.education), added our SSH keys to the `connector` user, disabled password authentication for SSH, disabled password requirement for `sudo` and configured unattended upgrades.

**Comment by zven** [comment]
@timber-they Thanks for the update! Regarding credentials etc.: We're still in the process of obtaining them.

**Comment by timber-they** [comment]
We now have the credentials, but for some reason TLS-requests to the backbone fail from our machine. This might be due to a blacklist we ended up on, so this ticket is waiting again.

**Comment by timber-they** [comment]
The person claims that no blacklist exists.

**Comment by timber-they** [comment]
Apparently we landed on some kind of Google Blocklist and they use Google for some stuff. Long story short, I've set up a new server and configured it and there it seems to work. The IP is 159.69.34.83 (try for example 159.69.34.83/health), the DNS entry will be adjusted soon by Christopher.
@zven is there anything else to do here? Or was it just about setting the server up?

**Comment by timber-they** [comment]
I guess it would make sense for the connector to be reachable via https, so I'm gonna set this up.

**Comment by zven** [comment]
@timber-they Great idea! 👍  In general, I would say that's it for this issue. I see the actual integration into our system as an extra issue (or rather series of issues).

**Comment by timber-they** [comment]
Alright, so there's no code to review, but you can check out the installation on connector.openbadges.education (`ssh` with `ssh ubuntu@connector.openbadges.education`).

**Comment by jona159** [comment]
@timber-they The configuration looks good to me! But i just tried to hit ```159.69.34.83/health``` with my phone and got back a 404. 
Also, have you considered using ```ferretDB``` instead of mongo? The enmeshed docs include an example for ```ferretDB``` [here](https://enmeshed.eu/operate/setup-with-docker-compose#option-3-docker-compose-with-ferretdb).

**Comment by timber-they** [comment]
@jona159 the 404 is because you didn't access it with https. If you would indeed try to access `https://159.69.34.83/health` then you'd get a warning that the ssl certificate is for the wrong site (because it's for `connector.openbadges.education`), but if you'd accept the risk it would work.
The more *typical* way to access it would be via `https://connector.openbadges.education/health`.

If this is fine for you, I'd then put this card to completed.

**Comment by jona159** [comment]
@timber-they okay i see, yes this card can be moved to ```Done```  then
