### ISSUE TITLE
server: adjust wording, colors and font in badge received email

### ISSUE THREAD

**Issue by zven** [mint-o-badges/badgr-server#75]
The badge received email is outdated. As a first step, we should adjust its wording and some smaller design elements (Asana ticket see here: https://app.asana.com/0/1205782519509072/1207098960931542/f)

Todos:

- new CI colours / font (Rubik)
- the sender in the header is "badgr-ui", which should be Open Educational Badges
- everything should be in German: 
  - instead of "Issued by" it should read "Vergeben von";
  - instead of "Sign In" it should read "Bei Open Educational Badges einloggen / registrieren";
  - instead of "New to Badging?" it should read "Neu bei Open Educational Badges?";
  - instead of "Learn more" it should read "Mehr erfahren" 
  -  "Unsubscribe" should read "Abmelden" BUT: Can't we simply remove this link since the user is not subscribed to a newsletter?
  - in the headline it should say "einen" badge instead of "ein" badge
- the "Learn More" currently links to "openbadges.org", this needs to be changed to openbadges.education

Nice to have:
- integrate new logo in a simple way (maybe just centered on top of the page?)

**Comment by YouQam** [comment]
I made the requested updates, including hiding `unsubscribe` and adding a logo at bottom. See attached iamge.

![Image](https://github.com/mint-o-badges/badgr-server/assets/40634685/2d326d86-b3cb-4dd4-9f90-b54381a70e0d)

**Comment by jona159** [comment]
Hey @YouQam, i merged this, because the mails were looking good when i tested with mailhog locally. Unfortunately on staging it does not seem to work as well yet: 

- The open badge logo is not shown
- It still shows ```Account erstellen``` in the button in Webmailer (weirdly in other mail clients the correct text is shown in the button)

Can you have another look at it? 
As a side note, i think  ```Abmelden``` (previously ```Unsubscribe``` ) can also be removed


![Image](https://github.com/mint-o-badges/badgr-server/assets/65068389/90a8936c-34c3-4245-a08e-ee028f19b608)

**Comment by YouQam** [comment]
This turned out to be a cache problem. But I think I'm close to find a solution for it. I've created a new ticket for this issue.
