### ISSUE TITLE
code formatting / prettier / linting for server (configuration)

### ISSUE THREAD

**Issue by zven** [mint-o-badges/badgr-server#86]
According to my knowledge, we have some mechanisms for this in the ui and the server project.

Todos:

- [ ] investigate and document in the readme of the respective projects what we use atm.
- [ ] in case something is missing: please introduce a system
- [ ] investigate commit message standards and prepare overview until Thursday so we can discuss this topic

**Comment by mpfeil** [comment]
Maybe also to introduce commit message standards as https://www.conventionalcommits.org/en/v1.0.0/

**Comment by jona159** [comment]
**UI:**
For the frontend we already have ```prettier```setup as a formatter. 
In the scope of this ticket, the ```commitlint``` package was introduced to stick to the ```angular commit message convention```. Instead of using ```git commit``` developers should now use the ```npx cz``` command. 

**Server: **
For the backend  ```pre-commit``` hooks are introduced to ensure code quality before commiting (see ```pre-commit-config.yml```). Developers need to install ```pre-commit``` and ```commitizen``` on their machines (see instructions in ReadME). 

In the ```pyproject.toml``` file you can find the following tools that are being used, as well as what rules are applied and ignored for each tool:

- [Black](https://github.com/psf/black) python formatter
- [Isort](https://pycqa.github.io/isort/) automatically fix order of imports 
- [djlint](https://www.djlint.com/) lint and format html templates in django
- [commitizen](https://pypi.org/project/commitizen/) commit convention

If you need to disable a rule in one file only, you can use comments such as e.g. ```# noqa <rule-number>```.  The rules from ```djlint``` for django templates seem to be especially strict. As they result in lots of errors, i disabled most of them in the ```pyproject.toml```. 

*Let me know if i should enable/disable certain rules*

**Comment by mpfeil** [comment]
@jona159 Are the commit messages always linted and you can´t commit anything unless you match the `angular commit message convention`?

**Comment by zven** [comment]
Review / merge this after re:publica release (potentially re-format again)

**Comment by timber-they** [comment]
@zven I guess this isn't `waiting` anymore, right? If I'm not mistaken the re:publica should be long over

**Comment by zven** [comment]
@timber-they Indeed, it's not in waiting anymore. It was actually in waiting because we first wanted to merge https://github.com/mint-o-badges/badgr-ui/issues/51 first before "changing" the whole backend with formatting commits. I think the way to do that is free now.
